#Command to run:
#docker-compose build
#docker-compose up -d

version: "3.8"

volumes:
  rabbitmq_data:

services:
  #################################
  # Availability
  #################################
  availability:
    build:
      context: ./
      dockerfile: availability/availability.Dockerfile
    image: marcsoh/availability:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/availability
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###############################################
  # Appointment
  ###############################################
  appointment:
    build:
      context: ./
      dockerfile: appointment/appointment.Dockerfile
    image: marcsoh/appointment:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/appointment
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
  
  ###############################################
  # Match
  ###############################################
  match:
    build:
      context: ./
      dockerfile: match/match.Dockerfile
    image: marcsoh/match:latest
    restart: always
    depends_on:
      - availability
      - appointment
    environment:
      availability_URL: http://availability:5001/availability
      appointment_URL: http://appointment:5005/appointment
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esdclinic-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ###############################################
  # Notification
  ###############################################
  notification:
    build:
      context: ./
      dockerfile: notification/notification.Dockerfile
    image: marcsoh/notification:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1


  ###############################################
  # Notify Patient
  ###############################################
  notify:
    build:
      context: ./
      dockerfile: notify/notify.Dockerfile
    image: marcsoh/notify:latest
    restart: always
    depends_on:
      - notification
      - appointment
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      appointment_URL: http://appointment:5005/appointment
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"
  
